Models/ModelZadania.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace projekt_v1._0.Models
{
    public class ModelZadania
    {
        [Key]
        [Display(Name = "Id zadania")]
        public int ZadanieId { get; set; }

        [Display(Name = "Data")]
        [Required(ErrorMessage = "To pole jest wymagane.")]
        public DateTime Data { get; set; }

        [Display(Name = "Start")]
        public TimeSpan? Start { get; set; }

        [Display(Name = "Koniec")]
        public TimeSpan? End { get; set; }

        [Display(Name = "Czy godzina wykonania zadania jest istotna?")]
        [Required(ErrorMessage = "To pole jest wymagane.")]
        public bool Hour { get; set; }

        [Display(Name = "Nazwa")]
        [Required(ErrorMessage = "To pole jest wymagane.")]
        public string Name { get; set; }

        [Display(Name = "Opis")]
        public string? Description { get; set; }

        [Display(Name = "Gotowe?")]
        public bool Done { get; set; }

        public string? UserId { get; set; }

        public virtual IdentityUser? User { get; set; }
    }
}

Controllers/ModelZadaniasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projekt_v1._0.Models;
using projekt_v4._0.Areas.Identity.Data;

namespace projekt_v4._0.Controllers
{
    [Authorize]
    public class ModelZadaniasController : Controller
    {
        private readonly UserDbContext _context;

        public ModelZadaniasController(UserDbContext context)
        {
            _context = context;
        }

        // GET: ModelZadanias
        public async Task<IActionResult> Index(DateTime? data)
        {
            var userDbContext = _context.ModelZadania.Include(m => m.User);
            

            ViewBag.Data = data;
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.Id = userId;

            if (data == null)
            {
                ViewBag.Data = DateTime.Today;
            }

            return View(await userDbContext.ToListAsync());
        }

        // GET: ModelZadanias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.Id = userId;


            if (id == null || _context.ModelZadania == null)
            {
                return NotFound();
            }


            var modelZadania = await _context.ModelZadania
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.ZadanieId == id);
            if (modelZadania == null)
            {
                return NotFound();
            }

            return View(modelZadania);
        }

        // GET: ModelZadanias/Create
        public IActionResult Create()
        {
            //ViewBag.Id = user.Id;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.Id = userId;

            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: ModelZadanias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ZadanieId,Data,Start,End,Hour,Name,Description,Done,UserId")] ModelZadania modelZadania)
        {
           
            if (ModelState.IsValid)
            {
                 _context.Add(modelZadania);
                 await _context.SaveChangesAsync();
                 return RedirectToAction(nameof(Index));
                
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", modelZadania.UserId);
            return View(modelZadania);
        }

        // GET: ModelZadanias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.ModelZadania == null)
            {
                return NotFound();
            }

            var modelZadania = await _context.ModelZadania.FindAsync(id);
            if (modelZadania == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.Id = userId;

            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", modelZadania.UserId);
            return View(modelZadania);
        }

        // POST: ModelZadanias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ZadanieId,Data,Start,End,Hour,Name,Description,Done,UserId")] ModelZadania modelZadania)
        {
            if (id != modelZadania.ZadanieId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(modelZadania);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelZadaniaExists(modelZadania.ZadanieId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", modelZadania.UserId);
            return View(modelZadania);
        }

        // GET: ModelZadanias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.Id = userId;

            if (id == null || _context.ModelZadania == null)
            {
                return NotFound();
            }

            var modelZadania = await _context.ModelZadania
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.ZadanieId == id);
            if (modelZadania == null)
            {
                return NotFound();
            }

            return View(modelZadania);
        }

        // POST: ModelZadanias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ModelZadania == null)
            {
                return Problem("Entity set 'UserDbContext.ModelZadania'  is null.");
            }
            var modelZadania = await _context.ModelZadania.FindAsync(id);
            if (modelZadania != null)
            {
                _context.ModelZadania.Remove(modelZadania);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Done(int id)
        {
           // ModelZadania zadanie = zadania.FirstOrDefault(x => x.ZadanieId == id);
           

            if (_context.ModelZadania == null)
            {
                return Problem("Entity set 'UserDbContext.ModelZadania'  is null.");
            }
            var modelZadania = await _context.ModelZadania.FindAsync(id);
            if (modelZadania != null)
            {
                if (modelZadania.Done == true) modelZadania.Done = false;
                else modelZadania.Done = true;
                _context.Update(modelZadania);
            }

            await _context.SaveChangesAsync();

           
            return base.RedirectToAction(nameof (Index));

        }


        private bool ModelZadaniaExists(int id)
        {
          return _context.ModelZadania.Any(e => e.ZadanieId == id);
        }
    }
}

Views/ModelZadanias/Create.cshtml
@model projekt_v1._0.Models.ModelZadania


@{
    ViewData["Title"] = "Stwórz zadanie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Stwórz zadanie</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" type="date"/>
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Hour" checked/> @Html.DisplayNameFor(model => model.Hour)
                </label>
            </div>



            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" type="time" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group" >
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" type="time" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
               
            
        
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserId" class="control-label" hidden></label>
                <input asp-for="UserId" class="form-control" value="@Convert.ToString(ViewBag.Id)" hidden/>
            </div>
            
            <div class="form-group">
                <button type="submit" class="btn btn-warning text-uppercase px-5" style="background:#890069; color:white;" onclick="location.href='@Url.Action("Index", "ModelZadanias")'">Utwórz</button>
                <button type="button" class="btn btn-warning text-uppercase px-5" style="background:#990075; color:white;" onclick="location.href='@Url.Action("Index", "ModelZadanias")'">Wróć do listy zadań</button>

            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ModelZadanias/Delete.cshtml
@model projekt_v1._0.Models.ModelZadania

@{
    ViewData["Title"] = "Usuń zadanie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    if (Model.UserId == ViewBag.Id)
    {

    <h1><span style="color:#990075 ;">Usuń zadanie</span></h1>

    <h3>Czy jesteś pewny, że chcesz ususnąć zdanie?</h3>
    <div>
            <hr />
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Data)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Data)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Start)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Start)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.End)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.End)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Hour)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Hour)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Done)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Done)
                </dd>
                <dt class = "col-sm-2" hidden>
                    @Html.DisplayNameFor(model => model.User)
                </dt>
                <dd class = "col-sm-10" hidden>
                    @Html.DisplayFor(model => model.User.Id)
                </dd>
            </dl>
            
            <form asp-action="Delete">
                <input type="hidden" asp-for="ZadanieId" />
                <input type="submit" value="Usuń" class="btn btn-danger" /> |
                <button type="button" class="btn btn-danger" style="background:#990075; color:white;" onclick="location.href='@Url.Action("Index", "ModelZadanias")'">Wróć do listy zadań</button>
            </form>
    </div>
}
}

@{
    if (Model.UserId != ViewBag.Id || Model.UserId == null)
    {
    <h1><span style="color:red ;"><b>Oszukista!</b></span></h1>
    <h3>Dlaczego próbujesz mnie oszukać?! To zadanie nie należy do Ciebie!!!</h3>
    <br>
    <img src="~/img/zly.png" style="max-height:250px" alt="zly" />
    }
}

Views/ModelZadanias/Details.cshtml
@model projekt_v1._0.Models.ModelZadania

@{
    ViewData["Title"] = "Szczegóły zadania";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (Model.UserId == ViewBag.Id)
    {

    <h1><span style="color:#990075 ;">Szczegóły zadania</span></h1>

    <div>

                <hr />
                <dl class="row">
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Data)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Data)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Start)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Start)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.End)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.End)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Hour)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Hour)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Description)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Done)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Done)
                    </dd>
                    @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>*@
                </dl>
    </div>
    <div>
            <a asp-action="Edit" class="btn btn-danger" style="background:#890069;" asp-route-id="@Model?.ZadanieId">Edytuj</a> |
            <a asp-action="Index"class="btn btn-danger" style="background:#990075;">Wróć do listy zadań</a>
            </div>
        }
    }


    @{
    if (Model.UserId != ViewBag.Id || Model.UserId==null)
    {
                <h1><span style="color:red ;"><b>Oszukista!</b></span></h1>
                <h3>Dlaczego próbujesz mnie oszukać?! To zadanie nie należy do Ciebie!!!</h3>
                <br>
                <img src="~/img/zly.png" style="max-height:250px" alt="zly" />
    }
    }

Views/ModelZadanias/Edit.cshtml
@model projekt_v1._0.Models.ModelZadania

@{
    ViewData["Title"] = "Edytuj zadanie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (Model.UserId == ViewBag.Id)
    {

     <h1><span style="color:#990075 ;">Edytuj zadanie</span></h1>

     <hr />
     <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ZadanieId" />


                <div class="form-group">
                    <label asp-for="Data" class="control-label"></label>
                    <input asp-for="Data" class="form-control" type="date" />
                    <span asp-validation-for="Data" class="text-danger"></span>
                </div>

                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Hour" /> @Html.DisplayNameFor(model => model.Hour)
                    </label>
                </div>

                <div class="form-group">
                    <label asp-for="Start" class="control-label"></label>
                    <input asp-for="Start" class="form-control" type="time" />
                    <span asp-validation-for="Start" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="End" class="control-label"></label>
                    <input asp-for="End" class="form-control" type="time" />
                    <span asp-validation-for="End" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label" hidden></label>
                    <input asp-for="UserId" class="form-control" value="@Convert.ToString(ViewBag.Id)" hidden/>
                </div>
                <br/>
                <div class="form-group">
                        <input type="submit" value="Zapisz" class="btn btn-danger" style="background:#890069;" />
                </div>


            </form>
        </div>
     </div>
     <br/>
     <div>
            <a asp-action="Index" class="btn btn-danger" style="background:#990075;">Wróć do listy</a>
     </div>

    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

    }
}

@{
    if (Model.UserId != ViewBag.Id || Model.UserId == null)
    {
        <h1><span style="color:red ;"><b>Oszukista!</b></span></h1>
        <h3>Dlaczego próbujesz mnie oszukać?! To zadanie nie należy do Ciebie!!!</h3>
        <br>
        <img src="~/img/zly.png" style="max-height:250px" alt="zly" />
    }
}